In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()
x=iris.data
y=iris.target
x.shape,y.shape

((150, 4), (150,))

In [4]:
np.unique(y)

array([0, 1, 2])

In [22]:
y=y.reshape(-1,1)
y.shape

(150, 1)

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
from keras.models import Sequential

In [12]:
model=Sequential()

In [13]:
## imput layer

In [14]:
from keras.layers import Dense
model.add(Dense(10,input_shape=(4,),activation="relu"))

In [15]:
model.add(Dense(20,activation='relu'))

In [16]:
model.add(Dense(3,activation='relu'))

In [30]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
y=y.reshape(-1,1)
new_y=one.fit_transform(y).toarray()
new_y[:3]

c:\users\anil.reddy.kunduru\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:414: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [32]:
model.compile(loss='categorical_crossentropy',optimizer='adam')

In [34]:
model.fit(x,new_y,epochs=100)

Epoch 1/100
150/150 [==============================] - 1s 6ms/step - loss: 5.7621
Epoch 2/100
150/150 [==============================] - 0s 160us/step - loss: 5.6731
Epoch 3/100
150/150 [==============================] - 0s 160us/step - loss: 5.5988
Epoch 4/100
150/150 [==============================] - 0s 260us/step - loss: 5.5332
Epoch 5/100
150/150 [==============================] - 0s 160us/step - loss: 5.4529
Epoch 6/100
150/150 [==============================] - 0s 147us/step - loss: 5.3865
Epoch 7/100
150/150 [==============================] - 0s 233us/step - loss: 5.3781
Epoch 8/100
150/150 [==============================] - 0s 167us/step - loss: 5.3740
Epoch 9/100
150/150 [==============================] - 0s 173us/step - loss: 5.3727
Epoch 10/100
150/150 [==============================] - 0s 193us/step - loss: 5.3727
Epoch 11/100
150/150 [==============================] - 0s 280us/step - loss: 5.3727
Epoch 12/100
150/150 [==============================] - 0s 147us/step - loss

Epoch 97/100
150/150 [==============================] - 0s 147us/step - loss: 5.3727
Epoch 98/100
150/150 [==============================] - 0s 147us/step - loss: 5.3727
Epoch 99/100
150/150 [==============================] - 0s 167us/step - loss: 5.3727
Epoch 100/100
150/150 [==============================] - 0s 180us/step - loss: 5.3727


In [45]:
model.predict_classes(x[70:110])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)