In [1]:
import pandas as pd
import numpy as np
# Get some time series data
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/timeseries.csv")
df.head()

Date      A       B       C      D      E      F      G
0  2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
1  2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2  2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
3  2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
4  2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

In [2]:
df.index=df.Date
df.head()

Date      A       B       C      D      E      F      G
Date                                                                     
2008-03-18  2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
2008-03-19  2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2008-03-20  2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
2008-03-25  2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
2008-03-26  2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

In [3]:
df.pop('Date')
df.head()

A       B       C      D      E      F      G
Date                                                         
2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87  63.44
2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76  59.98
2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04  59.61
2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84  59.41
2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02  60.09

In [4]:
Y=df['G']
df=df.drop(['G'],axis=1)
df.head()

A       B       C      D      E      F
Date                                                  
2008-03-18  24.68  164.93  114.73  26.27  19.21  28.87
2008-03-19  24.18  164.89  114.75  26.22  19.07  27.76
2008-03-20  23.99  164.63  115.04  25.78  19.01  27.04
2008-03-25  24.14  163.92  114.85  27.41  19.61  27.84
2008-03-26  24.44  163.45  114.84  26.86  19.53  28.02

In [5]:
df.values
df.shape

(11, 6)

In [7]:
Y

Date
2008-03-18    63.44
2008-03-19    59.98
2008-03-20    59.61
2008-03-25    59.41
2008-03-26    60.09
2008-03-27    59.62
2008-03-28    58.65
2008-03-31    59.20
2008-04-01    56.18
2008-04-02    56.64
2008-04-03    57.49
Name: G, dtype: float64

In [8]:
X=[]
y_train=[]
values=df.values
for i in range(len(values)):
    X.append([list(values[i])])
    y_train.append([Y[i]])

In [9]:
y_train

[[63.44],
 [59.98],
 [59.61],
 [59.41],
 [60.09],
 [59.62],
 [58.65],
 [59.2],
 [56.18],
 [56.64],
 [57.49]]

In [10]:
X

[[[24.68, 164.93, 114.73, 26.27, 19.21, 28.87]],
 [[24.18, 164.89, 114.75, 26.22, 19.07, 27.76]],
 [[23.99, 164.63, 115.04, 25.78, 19.01, 27.04]],
 [[24.14, 163.92, 114.85, 27.41, 19.61, 27.84]],
 [[24.44, 163.45, 114.84, 26.86, 19.53, 28.02]],
 [[24.38, 163.46, 115.4, 27.09, 19.72, 28.25]],
 [[24.32, 163.22, 115.56, 27.13, 19.63, 28.24]],
 [[24.19, 164.02, 115.54, 26.74, 19.55, 28.43]],
 [[23.81, 163.59, 115.72, 27.82, 20.21, 29.17]],
 [[24.03, 163.32, 115.11, 28.22, 20.42, 29.38]],
 [[24.34, 163.34, 115.17, 28.14, 20.36, 29.51]]]

In [11]:
df['X']=X

In [12]:
x_train=df['X'].cumsum()

In [13]:
X[2]

[[23.99, 164.63, 115.04, 25.78, 19.01, 27.04]]

In [14]:
x_train[2]

[[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],
 [24.18, 164.89, 114.75, 26.22, 19.07, 27.76],
 [23.99, 164.63, 115.04, 25.78, 19.01, 27.04]]

In [19]:
import keras

In [20]:
from keras.preprocessing.sequence import pad_sequences
x_train_new=pad_sequences(x_train,11)

In [21]:
x_train_new.shape

(11, 11, 6)

In [39]:
x_train[1]

[[24.68, 164.93, 114.73, 26.27, 19.21, 28.87],
 [24.18, 164.89, 114.75, 26.22, 19.07, 27.76]]

In [29]:
x_train_new[1]

array([[  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [ 24, 164, 114,  26,  19,  28],
       [ 24, 164, 114,  26,  19,  27]])

In [28]:
y_train=np.array(y_train)
y_train

array([[63.44],
       [59.98],
       [59.61],
       [59.41],
       [60.09],
       [59.62],
       [58.65],
       [59.2 ],
       [56.18],
       [56.64],
       [57.49]])

In [22]:
from keras.models import Sequential
from keras.layers import Dense,LSTM

In [2]:
help(LSTM)

Help on class LSTM in module keras.layers.recurrent:

class LSTM(RNN)
 |  LSTM(units, activation='tanh', recurrent_activation='hard_sigmoid', use_bias=True, kernel_initializer='glorot_uniform', recurrent_initializer='orthogonal', bias_initializer='zeros', unit_forget_bias=True, kernel_regularizer=None, recurrent_regularizer=None, bias_regularizer=None, activity_regularizer=None, kernel_constraint=None, recurrent_constraint=None, bias_constraint=None, dropout=0.0, recurrent_dropout=0.0, implementation=1, return_sequences=False, return_state=False, go_backwards=False, stateful=False, unroll=False, **kwargs)
 |  
 |  Long Short-Term Memory layer - Hochreiter 1997.
 |  
 |  # Arguments
 |      units: Positive integer, dimensionality of the output space.
 |      activation: Activation function to use
 |          (see [activations](../activations.md)).
 |          Default: hyperbolic tangent (`tanh`).
 |          If you pass `None`, no activation is applied
 |          (ie. "linear" activati

## input layer

In [23]:
s=x_train_new.shape
print(s)
model=Sequential()
model.add(LSTM(10,input_dim=s[2],input_length=s[1]))

(11, 11, 6)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(10, input_shape=(11, 6))`
  after removing the cwd from sys.path.


In [21]:
s

(11, 11, 6)

## hiden layer

In [24]:
model.add(Dense(10,activation='relu'))

## output layer

In [25]:
model.add(Dense(1))

In [26]:
model.compile(loss='mean_squared_error',optimizer='sgd')

In [30]:
history = model.fit(x_train_new, y_train,batch_size=11, epochs=300)


Epoch 1/300
11/11 [==============================] - 1s 59ms/step - loss: 3581.2056
Epoch 2/300
11/11 [==============================] - 0s 635us/step - loss: 3260.3088
Epoch 3/300
11/11 [==============================] - 0s 544us/step - loss: 2158.3479
Epoch 4/300
11/11 [==============================] - 0s 453us/step - loss: 1866.8387
Epoch 5/300
11/11 [==============================] - 0s 544us/step - loss: 3213.8303
Epoch 6/300
11/11 [==============================] - 0s 454us/step - loss: 3086.7014
Epoch 7/300
11/11 [==============================] - 0s 1ms/step - loss: 2964.6072
Epoch 8/300
11/11 [==============================] - 0s 453us/step - loss: 2847.3477
Epoch 9/300
11/11 [==============================] - 0s 997us/step - loss: 2734.7319
Epoch 10/300
11/11 [==============================] - 0s 635us/step - loss: 2626.5752
Epoch 11/300
11/11 [==============================] - 0s 544us/step - loss: 2522.7017
Epoch 12/300
11/11 [==============================] - 0s 816us/st

Epoch 96/300
11/11 [==============================] - 0s 635us/step - loss: 84.7344
Epoch 97/300
11/11 [==============================] - 0s 635us/step - loss: 81.5178
Epoch 98/300
11/11 [==============================] - 0s 635us/step - loss: 78.4286
Epoch 99/300
11/11 [==============================] - 0s 544us/step - loss: 75.4618
Epoch 100/300
11/11 [==============================] - 0s 544us/step - loss: 72.6125
Epoch 101/300
11/11 [==============================] - 0s 907us/step - loss: 69.8760
Epoch 102/300
11/11 [==============================] - 0s 907us/step - loss: 67.2478
Epoch 103/300
11/11 [==============================] - 0s 543us/step - loss: 64.7238
Epoch 104/300
11/11 [==============================] - 0s 635us/step - loss: 62.2997
Epoch 105/300
11/11 [==============================] - 0s 544us/step - loss: 59.9715
Epoch 106/300
11/11 [==============================] - 0s 635us/step - loss: 57.7356
Epoch 107/300
11/11 [==============================] - 0s 635us/step 

Epoch 194/300
11/11 [==============================] - 0s 635us/step - loss: 5.0575
Epoch 195/300
11/11 [==============================] - 0s 635us/step - loss: 4.9961
Epoch 196/300
11/11 [==============================] - 0s 544us/step - loss: 4.9372
Epoch 197/300
11/11 [==============================] - 0s 500us/step - loss: 4.8807
Epoch 198/300
11/11 [==============================] - 0s 635us/step - loss: 4.8263
Epoch 199/300
11/11 [==============================] - 0s 544us/step - loss: 4.7742
Epoch 200/300
11/11 [==============================] - 0s 1ms/step - loss: 4.7241
Epoch 201/300
11/11 [==============================] - 0s 635us/step - loss: 4.6759
Epoch 202/300
11/11 [==============================] - 0s 635us/step - loss: 4.6297
Epoch 203/300
11/11 [==============================] - 0s 2ms/step - loss: 4.5853
Epoch 204/300
11/11 [==============================] - 0s 635us/step - loss: 4.5427
Epoch 205/300
11/11 [==============================] - 0s 544us/step - loss: 4.5

Epoch 293/300
11/11 [==============================] - 0s 907us/step - loss: 3.5370
Epoch 294/300
11/11 [==============================] - 0s 725us/step - loss: 3.5359
Epoch 295/300
11/11 [==============================] - 0s 1ms/step - loss: 3.5348
Epoch 296/300
11/11 [==============================] - 0s 725us/step - loss: 3.5338
Epoch 297/300
11/11 [==============================] - 0s 635us/step - loss: 3.5328
Epoch 298/300
11/11 [==============================] - 0s 544us/step - loss: 3.5318
Epoch 299/300
11/11 [==============================] - 0s 725us/step - loss: 3.5309
Epoch 300/300
11/11 [==============================] - 0s 635us/step - loss: 3.5300


In [31]:
model.predict(x_train_new)

array([[58.97581],
       [58.97581],
       [58.97581],
       [58.97581],
       [58.97581],
       [58.97581],
       [58.97581],
       [58.97581],
       [58.97581],
       [58.97581],
       [58.97581]], dtype=float32)

In [32]:
y_train

array([[63.44],
       [59.98],
       [59.61],
       [59.41],
       [60.09],
       [59.62],
       [58.65],
       [59.2 ],
       [56.18],
       [56.64],
       [57.49]])

In [79]:
model.save("lstm.h5")

In [81]:
from keras.models import load_model
saved_model=load_model('lstm.h5')