# forward propagation

In [1]:
import numpy as np
input_data=np.array([1,2])
weights=np.array([[2,1],[1,-1],[2,-1]])
node1=(input_data*weights[0]).sum()
node2=(input_data*weights[1]).sum()
node1,node2

(4, -1)

In [2]:
weights[1]

array([ 1, -1])

In [3]:
hidden=np.array([node1,node2])
output=(hidden*weights[2]).sum()
output

9

# Activation Funtions capture pattrens in non linear Data

In [7]:
def relu(input):
    return max(input,0)

In [ ]:
node1=(input_data*weights[0]).sum()
node2=(input_data*weights[1]).sum()

In [3]:
hidden=np.array([relu(node1),relu(node2)])
output=(hidden*weights[2]).sum()
output

8

# calculating error

In [4]:
predicted=output
actual=3
error=predicted-actual
error

5

# find slope

In [5]:
slope=2*input_data*error
slope 

array([10, 20])

In [20]:
learning_rate = 0.01
new_weights=weights - (slope*learning_rate)
new_weights

array([[ 1.9,  0.8],
       [ 0.9, -1.2],
       [ 1.9, -1.2]])

In [21]:
node1=(input_data*new_weights[0]).sum()
node2=(input_data*new_weights[1]).sum()
hidden=np.array([relu(node1),relu(node2)])
output=(hidden*weights[2]).sum()
output

7.0

# learning

In [12]:
def learning(input_data,weights,actual=3,learning_rate=0.01,n=20):
    for i in range(n):
        node1=(input_data*weights[0]).sum()
        node2=(input_data*weights[1]).sum()
        hidden=np.array([relu(node1),relu(node2)])
        predicted=(hidden*weights[2]).sum()
        error=predicted-actual
        slope=2*input_data*error
        weights=weights - (slope*learning_rate)
    return weights,predicted

In [13]:
weights,predicted=learning(input_data,weights,actual=3,learning_rate=0.01,n=200)

In [14]:
weights

array([[ 1.5797959 ,  0.15959179],
       [ 0.5797959 , -1.84040821],
       [ 1.5797959 , -1.84040821]])

In [15]:
predicted

3.0

# BAckword propagation

In [ ]:
# calulate a(j)-y = Q
# error of activation funtion slope subtrated from actual.
#sohastic Gradent decent.